Repository eritbh/yuuko, pull requests merged in 2019-10, with the labels that each got.

#34 Command event changes
  src/Client.ts
Labels: changes: api, type: enhancement, type: style, version: major

#31 Add invalidCommand emit
  src/Client.ts
Labels: changes: api, type: enhancement, version: minor

#30 Use Eris.Message as message type in requirements
  src/Command.ts
Labels: changes: api, type: bug, version: patch

#35 Remove setavatar command
  docs/commands.md
  package.json
  src/commands/index.ts
  src/commands/setavatar.ts
Labels: changes: command, version: major
